# Generated by Django 3.0.7 on 2020-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_G_Recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='model_pic',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_picture/'),
        ),
    ]
